[package]
name = "netidx-admin"
version = "0.32.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2024"
license = "MIT"
description = "netidx administrative control plane engine"
homepage = "https://netidx.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
readme = "../README.md"
documentation = "https://docs.rs/netidx-admin"
keywords = ["networking", "distributed", "configuration"]
categories = ["network-programming"]

[features]
default = []
cloud-detect = ["dep:reqwest", "dep:if-addrs"]

[dependencies]
anyhow = { workspace = true }
arcstr = { workspace = true }
async-trait = { workspace = true }
compact_str = { workspace = true }
dirs = { workspace = true }
netidx = { path = "../netidx", version = "0.32.0", default-features = false }
netidx-activation = { path = "../netidx-activation", version = "0.32.0" }
netidx-id-map = { path = "../netidx-id-map", version = "0.32.0" }
netidx-tpm = { path = "../netidx-tpm", version = "0.32.0" }
parking_lot = { workspace = true }
rustls-pemfile = { workspace = true }
x509-parser = { workspace = true, features = ["verify"] }
log = { workspace = true }
mdns-sd = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
humantime = { workspace = true }
humantime-serde = { workspace = true }
sha2 = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }
globset = { workspace = true }
base64 = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
rcgen = { workspace = true, features = ["x509-parser"] }
reqwest = { workspace = true, optional = true }
if-addrs = { workspace = true, optional = true }
futures = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["user"] }
openssl = { workspace = true }
aes-gcm = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
time = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
env_logger = { workspace = true }
