use tui;
use tui::text;

let colors = [
   `Red,
   `Green,
   `Yellow,
   `Blue,
   `Magenta,
   `Cyan,
   `Gray,
   `DarkGray,
   `LightRed,
   `LightGreen,
   `LightYellow,
   `LightBlue,
   `LightMagenta,
   `LightCyan
];
let clock = time::timer(1, true);
let style = tui::style(#fg: rand::pick(clock ~ colors));
let hello = span(#style, "Hello");
let style = tui::style(#fg: rand::pick(clock ~ colors));
let world = span(#style, " World!");
text(&[line([hello, world])])
