use tui;
use tui::paragraph;
use tui::tabs;

let clock = time::timer(duration:1.0s, true);
let selected = 0;
selected <- ((clock ~ selected) + 1) % 3;

let tab1 = paragraph(&"This is tab 1");
let tab2 = paragraph(&"This is tab 2");
let tab3 = paragraph(&"This is tab 3");

tabs(
  #highlight_style: &style(#fg:`Yellow),
  #selected: &selected,
  &[
    (line("One"), tab1),
    (line("Two"), tab2),
    (line("Three"), tab3)
  ]
)
