/* Generated by cbindgen — do not edit */

#ifndef NETIDX_H
#define NETIDX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Discriminant for subscriber events.
 */
enum NetidxEventType
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    NETIDX_EVENT_TYPE_UNSUBSCRIBED = 0,
    NETIDX_EVENT_TYPE_UPDATE = 1,
};
#ifndef __cplusplus
typedef uint8_t NetidxEventType;
#endif // __cplusplus

/**
 * Discriminant tag for Value, matching the Rust enum's discriminants.
 */
enum NetidxValueType
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
    NETIDX_VALUE_TYPE_U8 = 1,
    NETIDX_VALUE_TYPE_I8 = 2,
    NETIDX_VALUE_TYPE_U16 = 4,
    NETIDX_VALUE_TYPE_I16 = 8,
    NETIDX_VALUE_TYPE_U32 = 16,
    NETIDX_VALUE_TYPE_V32 = 32,
    NETIDX_VALUE_TYPE_I32 = 64,
    NETIDX_VALUE_TYPE_Z32 = 128,
    NETIDX_VALUE_TYPE_U64 = 256,
    NETIDX_VALUE_TYPE_V64 = 512,
    NETIDX_VALUE_TYPE_I64 = 1024,
    NETIDX_VALUE_TYPE_Z64 = 2048,
    NETIDX_VALUE_TYPE_F32 = 4096,
    NETIDX_VALUE_TYPE_F64 = 8192,
    NETIDX_VALUE_TYPE_BOOL = 16384,
    NETIDX_VALUE_TYPE_NULL = 32768,
    NETIDX_VALUE_TYPE_STRING = 2147483648,
    NETIDX_VALUE_TYPE_BYTES = 1073741824,
    NETIDX_VALUE_TYPE_ERROR = 536870912,
    NETIDX_VALUE_TYPE_ARRAY = 268435456,
    NETIDX_VALUE_TYPE_MAP = 134217728,
    NETIDX_VALUE_TYPE_DECIMAL = 67108864,
    NETIDX_VALUE_TYPE_DATE_TIME = 33554432,
    NETIDX_VALUE_TYPE_DURATION = 16777216,
    NETIDX_VALUE_TYPE_ABSTRACT = 8388608,
};
#ifndef __cplusplus
typedef uint32_t NetidxValueType;
#endif // __cplusplus

typedef struct NetidxChannelClientConn NetidxChannelClientConn;

typedef struct NetidxChannelListener NetidxChannelListener;

typedef struct NetidxChannelServerConn NetidxChannelServerConn;

/**
 * Opaque handle to a Config.
 */
typedef struct NetidxConfig NetidxConfig;

typedef struct NetidxDval NetidxDval;

typedef struct NetidxEvent NetidxEvent;

/**
 * Opaque handle to a Path.
 */
typedef struct NetidxPath NetidxPath;

typedef struct NetidxPublisher NetidxPublisher;

typedef struct NetidxPublisherBuilder NetidxPublisherBuilder;

typedef struct NetidxPublisherVal NetidxPublisherVal;

typedef struct NetidxRpcCall NetidxRpcCall;

typedef struct NetidxRpcClient NetidxRpcClient;

typedef struct NetidxRpcProc NetidxRpcProc;

/**
 * Opaque handle to a tokio runtime.
 */
typedef struct NetidxRuntime NetidxRuntime;

typedef struct NetidxSubscriber NetidxSubscriber;

typedef struct NetidxSubscriberBuilder NetidxSubscriberBuilder;

/**
 * An update from the update receiver, pairing a SubId with an Event.
 */
typedef struct NetidxSubscriberUpdate NetidxSubscriberUpdate;

typedef struct NetidxUpdateBatch NetidxUpdateBatch;

typedef struct NetidxUpdateReceiver NetidxUpdateReceiver;

/**
 * Opaque handle to a Value on the Rust heap.
 */
typedef struct NetidxValue NetidxValue;

typedef struct NetidxWriteReceiver NetidxWriteReceiver;

/**
 * A single write request from a subscriber.
 */
typedef struct NetidxWriteRequest NetidxWriteRequest;

/**
 * Opaque error type. NULL means no error.
 * The caller must free with `netidx_error_free`.
 */
typedef struct NetidxError {
    char *msg;
} NetidxError;

/**
 * Argument specification for an RPC procedure.
 */
typedef struct NetidxArgSpec {
    /**
     * Argument name (UTF-8, not null-terminated)
     */
    const char *name;
    uintptr_t name_len;
    /**
     * Documentation value (owned, consumed)
     */
    struct NetidxValue *doc;
    /**
     * Default value (owned, consumed)
     */
    struct NetidxValue *default_value;
} NetidxArgSpec;

/**
 * C function pointer type for RPC handlers.
 * `userdata` is the opaque pointer passed at registration.
 * `call` is the RPC call handle — the handler must call netidx_rpc_call_reply
 * to send a response. The call is consumed by reply.
 */
typedef void (*NetidxRpcHandler)(void *userdata, struct NetidxRpcCall *call);

/**
 * An argument for an RPC call.
 */
typedef struct NetidxRpcArg {
    const char *name;
    uintptr_t name_len;
    /**
     * Owned value, consumed by the call.
     */
    struct NetidxValue *value;
} NetidxRpcArg;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new channel listener.
 * Does not consume `pub_` or `path`.
 * `timeout_ms`: timeout for individual connections, -1 = no timeout.
 * Returns NULL on failure.
 */
struct NetidxChannelListener *netidx_channel_listener_new(const struct NetidxRuntime *rt,
                                                          const struct NetidxPublisher *pub_,
                                                          const struct NetidxPath *path,
                                                          int64_t timeout_ms,
                                                          struct NetidxError *err);

/**
 * Accept a new connection from the listener. Blocks until a client connects.
 * `timeout_ms`: -1 = no timeout.
 * Returns NULL on failure.
 */
struct NetidxChannelServerConn *netidx_channel_listener_accept(const struct NetidxRuntime *rt,
                                                               struct NetidxChannelListener *listener,
                                                               int64_t timeout_ms,
                                                               struct NetidxError *err);

/**
 * Destroy a channel listener.
 */
void netidx_channel_listener_destroy(struct NetidxChannelListener *l);

/**
 * Send one value to the client. Blocks until sent.
 * Consumes `value`.
 */
bool netidx_channel_server_conn_send_one(const struct NetidxRuntime *rt,
                                         const struct NetidxChannelServerConn *conn,
                                         struct NetidxValue *value,
                                         struct NetidxError *err);

/**
 * Receive one value from the client. Blocks until a value arrives.
 * `timeout_ms`: -1 = no timeout.
 * Returns a new owned Value, or NULL on error.
 */
struct NetidxValue *netidx_channel_server_conn_recv_one(const struct NetidxRuntime *rt,
                                                        const struct NetidxChannelServerConn *conn,
                                                        int64_t timeout_ms,
                                                        struct NetidxError *err);

/**
 * Check if the server connection is dead.
 */
bool netidx_channel_server_conn_is_dead(const struct NetidxChannelServerConn *conn);

/**
 * Destroy a server connection.
 */
void netidx_channel_server_conn_destroy(struct NetidxChannelServerConn *conn);

/**
 * Connect to a channel endpoint. Blocks until connected.
 * Does not consume `sub` or `path`.
 * Returns NULL on failure.
 */
struct NetidxChannelClientConn *netidx_channel_client_connect(const struct NetidxRuntime *rt,
                                                              const struct NetidxSubscriber *sub,
                                                              const struct NetidxPath *path,
                                                              struct NetidxError *err);

/**
 * Send a value to the server. Non-blocking (queues the write).
 * Consumes `value`.
 */
bool netidx_channel_client_conn_send(const struct NetidxChannelClientConn *conn,
                                     struct NetidxValue *value,
                                     struct NetidxError *err);

/**
 * Flush previously sent values, blocking until they reach OS buffers.
 */
bool netidx_channel_client_conn_flush(const struct NetidxRuntime *rt,
                                      const struct NetidxChannelClientConn *conn,
                                      struct NetidxError *err);

/**
 * Receive one value from the server. Blocks until a value arrives.
 * `timeout_ms`: -1 = no timeout.
 * Returns a new owned Value, or NULL on error.
 */
struct NetidxValue *netidx_channel_client_conn_recv_one(const struct NetidxRuntime *rt,
                                                        const struct NetidxChannelClientConn *conn,
                                                        int64_t timeout_ms,
                                                        struct NetidxError *err);

/**
 * Check if the client connection is dead.
 */
bool netidx_channel_client_conn_is_dead(const struct NetidxChannelClientConn *conn);

/**
 * Destroy a client connection.
 */
void netidx_channel_client_conn_destroy(struct NetidxChannelClientConn *conn);

/**
 * Load config from the default platform-specific location.
 * Returns NULL on failure.
 */
struct NetidxConfig *netidx_config_load_default(struct NetidxError *err);

/**
 * Load config from a specific file path.
 * `path` is a UTF-8 string of `len` bytes (not null-terminated).
 * Returns NULL on failure.
 */
struct NetidxConfig *netidx_config_load(const char *path,
                                        uintptr_t path_len,
                                        struct NetidxError *err);

/**
 * Clone a Config.
 */
struct NetidxConfig *netidx_config_clone(const struct NetidxConfig *cfg);

/**
 * Destroy a Config.
 */
void netidx_config_destroy(struct NetidxConfig *cfg);

/**
 * Create a zeroed error for use from C
 */
struct NetidxError netidx_error_init(void);

/**
 * Get the error message. Returns NULL if no error. The returned pointer
 * is valid until the next call to `netidx_error_free`.
 */
const char *netidx_error_message(const struct NetidxError *err);

/**
 * Free the error message. Safe to call on a zeroed error.
 */
void netidx_error_free(struct NetidxError *err);

/**
 * Create a Path from a UTF-8 byte range. Does not need null termination.
 */
struct NetidxPath *netidx_path_new(const char *data, uintptr_t len);

/**
 * Append a segment to a path, returning a new Path. Does not consume `base`.
 */
struct NetidxPath *netidx_path_append(const struct NetidxPath *base,
                                      const char *segment,
                                      uintptr_t segment_len);

/**
 * Get the string representation of a path. Borrows from the Path handle.
 * Valid while the Path lives.
 */
void netidx_path_as_str(const struct NetidxPath *path, const char **data, uintptr_t *len);

/**
 * Get the number of levels (components) in the path.
 */
uintptr_t netidx_path_levels(const struct NetidxPath *path);

/**
 * Get the basename (last component) of the path.
 * Returns false if the path has no basename (e.g. "/").
 */
bool netidx_path_basename(const struct NetidxPath *path, const char **data, uintptr_t *len);

/**
 * Get the dirname (parent path) of the path.
 * Returns false if the path has no parent (e.g. "/").
 */
bool netidx_path_dirname(const struct NetidxPath *path, const char **data, uintptr_t *len);

/**
 * Clone a Path.
 */
struct NetidxPath *netidx_path_clone(const struct NetidxPath *path);

/**
 * Destroy a Path.
 */
void netidx_path_destroy(struct NetidxPath *path);

/**
 * Create a new PublisherBuilder. Does not consume `cfg`.
 */
struct NetidxPublisherBuilder *netidx_publisher_builder_new(const struct NetidxConfig *cfg);

/**
 * Set the bind config from a string (e.g. "local", "192.168.0.0/24").
 * Returns true on success.
 */
bool netidx_publisher_builder_bind_cfg(struct NetidxPublisherBuilder *pb,
                                       const char *bind,
                                       uintptr_t bind_len,
                                       struct NetidxError *err);

/**
 * Set max clients.
 */
void netidx_publisher_builder_max_clients(struct NetidxPublisherBuilder *pb, uintptr_t max_clients);

/**
 * Set slack (max queued batches per client).
 */
void netidx_publisher_builder_slack(struct NetidxPublisherBuilder *pb, uintptr_t slack);

/**
 * Build the publisher. Consumes the builder. Returns NULL on failure.
 */
struct NetidxPublisher *netidx_publisher_builder_build(const struct NetidxRuntime *rt,
                                                       struct NetidxPublisherBuilder *pb,
                                                       struct NetidxError *err);

/**
 * Destroy the builder without building (e.g. on error path).
 */
void netidx_publisher_builder_destroy(struct NetidxPublisherBuilder *pb);

/**
 * Publish a value at a path. Consumes `init` (the initial value) and `path`.
 * Returns NULL on failure.
 */
struct NetidxPublisherVal *netidx_publisher_publish(const struct NetidxPublisher *pub_,
                                                    struct NetidxPath *path,
                                                    struct NetidxValue *init,
                                                    struct NetidxError *err);

/**
 * Publish a value with a write channel, so you can receive writes from subscribers.
 * Consumes `init` and `path`. Returns NULL on failure.
 * `channel_buffer`: channel capacity; 0 uses the default.
 * `write_rx` is an out-parameter: on success, receives a write receiver handle.
 */
struct NetidxPublisherVal *netidx_publisher_publish_with_writes(const struct NetidxPublisher *pub_,
                                                                struct NetidxPath *path,
                                                                struct NetidxValue *init,
                                                                uintptr_t channel_buffer,
                                                                struct NetidxWriteReceiver **write_rx,
                                                                struct NetidxError *err);

/**
 * Register to receive writes for an already-published value.
 * `channel_buffer`: channel capacity; 0 uses the default.
 * Returns a write receiver. The `val` is borrowed (not consumed).
 */
struct NetidxWriteReceiver *netidx_publisher_writes(const struct NetidxPublisher *pub_,
                                                    const struct NetidxPublisherVal *val,
                                                    uintptr_t channel_buffer);

/**
 * Start an update batch.
 */
struct NetidxUpdateBatch *netidx_publisher_start_batch(const struct NetidxPublisher *pub_);

/**
 * Wait until all previously published paths are registered with the resolver.
 */
void netidx_publisher_flushed(const struct NetidxRuntime *rt, const struct NetidxPublisher *pub_);

/**
 * Clone a publisher handle (Arc clone, cheap).
 */
struct NetidxPublisher *netidx_publisher_clone(const struct NetidxPublisher *pub_);

/**
 * Destroy a publisher.
 */
void netidx_publisher_destroy(struct NetidxPublisher *pub_);

/**
 * Update a published value in a batch. Consumes `value`.
 */
void netidx_publisher_val_update(const struct NetidxPublisherVal *val,
                                 struct NetidxUpdateBatch *batch,
                                 struct NetidxValue *value);

/**
 * Update a published value only if it changed. Consumes `value`.
 */
void netidx_publisher_val_update_changed(const struct NetidxPublisherVal *val,
                                         struct NetidxUpdateBatch *batch,
                                         struct NetidxValue *value);

/**
 * Destroy a published value handle. This will unpublish the value.
 */
void netidx_publisher_val_destroy(struct NetidxPublisherVal *val);

/**
 * Commit an update batch. Consumes the batch.
 * `timeout_ms`: timeout in milliseconds, -1 = no timeout.
 */
void netidx_update_batch_commit(const struct NetidxRuntime *rt,
                                struct NetidxUpdateBatch *batch,
                                int64_t timeout_ms);

/**
 * Destroy a batch without committing.
 */
void netidx_update_batch_destroy(struct NetidxUpdateBatch *batch);

/**
 * Try to receive write requests without blocking.
 * Returns at most one batch. `out_len` receives the count.
 * Returns NULL if no writes are available. The returned array and its
 * elements must be freed by the caller.
 */
struct NetidxWriteRequest **netidx_write_receiver_try_recv(struct NetidxWriteReceiver *rx,
                                                           uintptr_t *out_len);

/**
 * Receive write requests, blocking up to `timeout_ms` (-1 = forever).
 * Returns an array of write requests. `out_len` receives the count.
 * Returns NULL on timeout or channel closed.
 */
struct NetidxWriteRequest **netidx_write_receiver_recv(const struct NetidxRuntime *rt,
                                                       struct NetidxWriteReceiver *rx,
                                                       int64_t timeout_ms,
                                                       uintptr_t *out_len);

/**
 * Get the path from a write request. Borrows from the request.
 */
void netidx_write_request_path(const struct NetidxWriteRequest *req,
                               const char **data,
                               uintptr_t *len);

/**
 * Get the value from a write request. Returns a new owned Value (clone).
 */
struct NetidxValue *netidx_write_request_value(const struct NetidxWriteRequest *req);

/**
 * Destroy a write request.
 */
void netidx_write_request_destroy(struct NetidxWriteRequest *req);

/**
 * Free an array of write request pointers returned by recv/try_recv.
 * Does NOT free the individual requests — call netidx_write_request_destroy on each first.
 */
void netidx_write_request_array_free(struct NetidxWriteRequest **arr, uintptr_t len);

/**
 * Destroy a write receiver.
 */
void netidx_write_receiver_destroy(struct NetidxWriteReceiver *rx);

/**
 * Create a new RPC procedure on the publisher.
 * `args` and `args_len`: array of argument specs (consumed).
 * `handler`: C callback invoked for each call.
 * `userdata`: opaque pointer passed to handler.
 * Returns NULL on failure.
 */
struct NetidxRpcProc *netidx_rpc_proc_new(const struct NetidxPublisher *pub_,
                                          struct NetidxPath *path,
                                          struct NetidxValue *doc,
                                          const struct NetidxArgSpec *args,
                                          uintptr_t args_len,
                                          NetidxRpcHandler handler,
                                          void *userdata,
                                          struct NetidxError *err);

/**
 * Take an argument value from an RPC call by name, removing it.
 * Returns a new owned Value, or NULL if the argument is not present or `call` is null.
 */
struct NetidxValue *netidx_rpc_call_take_arg(struct NetidxRpcCall *call,
                                             const char *name,
                                             uintptr_t name_len);

/**
 * Reply to an RPC call with a value. Consumes both the call and the value.
 * No-op if either `call` or `value` is null.
 */
void netidx_rpc_call_reply(struct NetidxRpcCall *call, struct NetidxValue *value);

/**
 * Destroy an RPC call without replying (sends an error to the caller).
 */
void netidx_rpc_call_destroy(struct NetidxRpcCall *call);

/**
 * Destroy an RPC procedure (unpublishes it).
 */
void netidx_rpc_proc_destroy(struct NetidxRpcProc *proc_);

/**
 * Create a new RPC client for calling a remote procedure.
 * Does not consume `path` or `sub`.
 * Returns NULL on failure.
 */
struct NetidxRpcClient *netidx_rpc_client_new(const struct NetidxSubscriber *sub,
                                              const struct NetidxPath *path,
                                              struct NetidxError *err);

/**
 * Call an RPC procedure. Blocks until a reply is received.
 * `args` and `args_len`: array of arguments (values consumed).
 * `timeout_ms`: -1 = no timeout.
 * Returns a new owned Value, or NULL on error.
 */
struct NetidxValue *netidx_rpc_client_call(const struct NetidxRuntime *rt,
                                           const struct NetidxRpcClient *client,
                                           const struct NetidxRpcArg *args,
                                           uintptr_t args_len,
                                           int64_t timeout_ms,
                                           struct NetidxError *err);

/**
 * Clone an RPC client.
 */
struct NetidxRpcClient *netidx_rpc_client_clone(const struct NetidxRpcClient *client);

/**
 * Destroy an RPC client.
 */
void netidx_rpc_client_destroy(struct NetidxRpcClient *client);

/**
 * Create a new tokio multi-threaded runtime.
 * `worker_threads`: number of worker threads, 0 = use tokio default (number of cores).
 * Returns NULL on failure.
 */
struct NetidxRuntime *netidx_runtime_new(uintptr_t worker_threads, struct NetidxError *err);

/**
 * Destroy the runtime. All outstanding work will be cancelled.
 * Consumes the handle.
 */
void netidx_runtime_destroy(struct NetidxRuntime *rt);

/**
 * Create a new SubscriberBuilder. Does not consume `cfg`.
 */
struct NetidxSubscriberBuilder *netidx_subscriber_builder_new(const struct NetidxConfig *cfg);

/**
 * Build the subscriber. Consumes the builder. Returns NULL on failure.
 */
struct NetidxSubscriber *netidx_subscriber_builder_build(struct NetidxSubscriberBuilder *sb,
                                                         struct NetidxError *err);

/**
 * Destroy builder without building.
 */
void netidx_subscriber_builder_destroy(struct NetidxSubscriberBuilder *sb);

/**
 * Subscribe to a path, creating a durable subscription. Does not consume `path`.
 */
struct NetidxDval *netidx_subscriber_subscribe(const struct NetidxSubscriber *sub,
                                               const struct NetidxPath *path);

/**
 * Subscribe with an update channel, so you can receive all updates.
 * Returns a Dval and an update receiver via out-parameter.
 * `channel_buffer`: channel capacity; 0 uses the default.
 */
struct NetidxDval *netidx_subscriber_subscribe_updates(const struct NetidxSubscriber *sub,
                                                       const struct NetidxPath *path,
                                                       uintptr_t channel_buffer,
                                                       struct NetidxUpdateReceiver **update_rx);

/**
 * Clone a subscriber handle (cheap Arc clone).
 */
struct NetidxSubscriber *netidx_subscriber_clone(const struct NetidxSubscriber *sub);

/**
 * Destroy a subscriber.
 */
void netidx_subscriber_destroy(struct NetidxSubscriber *sub);

/**
 * Wait for the durable subscription to be connected.
 * `timeout_ms`: timeout in milliseconds, -1 = no timeout.
 * Returns true on success, false on error.
 */
bool netidx_dval_wait_subscribed(const struct NetidxRuntime *rt,
                                 const struct NetidxDval *dval,
                                 int64_t timeout_ms,
                                 struct NetidxError *err);

/**
 * Get the last event for a durable subscription.
 * Returns a new owned event handle. Caller must free with netidx_event_destroy.
 */
struct NetidxEvent *netidx_dval_last(const struct NetidxDval *dval);

/**
 * Get the unique subscription ID for a Dval, for matching against SubscriberUpdate.
 */
uint64_t netidx_dval_id(const struct NetidxDval *dval);

/**
 * Write a value back to the publisher through this subscription.
 * Consumes `value`. Returns true if sent immediately, false if queued.
 */
bool netidx_dval_write(const struct NetidxDval *dval, struct NetidxValue *value);

/**
 * Clone a Dval.
 */
struct NetidxDval *netidx_dval_clone(const struct NetidxDval *dval);

/**
 * Destroy a Dval (unsubscribes).
 */
void netidx_dval_destroy(struct NetidxDval *dval);

/**
 * Get the event type.
 */
NetidxEventType netidx_event_type(const struct NetidxEvent *ev);

/**
 * Clone the value from an Update event. Returns a new owned Value.
 * Returns NULL if the event is Unsubscribed.
 */
struct NetidxValue *netidx_event_value_clone(const struct NetidxEvent *ev);

/**
 * Destroy an event.
 */
void netidx_event_destroy(struct NetidxEvent *ev);

/**
 * Get the raw subscription ID from an update.
 */
uint64_t netidx_subscriber_update_sub_id(const struct NetidxSubscriberUpdate *update);

/**
 * Get the event type from an update.
 */
NetidxEventType netidx_subscriber_update_event_type(const struct NetidxSubscriberUpdate *update);

/**
 * Clone the value from an update's event. Returns NULL if Unsubscribed.
 */
struct NetidxValue *netidx_subscriber_update_value_clone(const struct NetidxSubscriberUpdate *update);

/**
 * Destroy a subscriber update.
 */
void netidx_subscriber_update_destroy(struct NetidxSubscriberUpdate *update);

/**
 * Free an array of subscriber update pointers. Does NOT free individual updates.
 */
void netidx_subscriber_update_array_free(struct NetidxSubscriberUpdate **arr, uintptr_t len);

/**
 * Try to receive subscriber updates without blocking.
 * Returns at most one batch. `out_len` receives the count.
 * Returns NULL if no updates are available.
 */
struct NetidxSubscriberUpdate **netidx_update_receiver_try_recv(struct NetidxUpdateReceiver *rx,
                                                                uintptr_t *out_len);

/**
 * Receive subscriber updates, blocking up to `timeout_ms` (-1 = forever).
 * Returns one batch. `out_len` receives the count.
 * Returns NULL on timeout or channel closed.
 */
struct NetidxSubscriberUpdate **netidx_update_receiver_recv(const struct NetidxRuntime *rt,
                                                            struct NetidxUpdateReceiver *rx,
                                                            int64_t timeout_ms,
                                                            uintptr_t *out_len);

/**
 * Destroy an update receiver.
 */
void netidx_update_receiver_destroy(struct NetidxUpdateReceiver *rx);

struct NetidxValue *netidx_value_null(void);

struct NetidxValue *netidx_value_u8(uint8_t v);

struct NetidxValue *netidx_value_i8(int8_t v);

struct NetidxValue *netidx_value_u16(uint16_t v);

struct NetidxValue *netidx_value_i16(int16_t v);

struct NetidxValue *netidx_value_u32(uint32_t v);

struct NetidxValue *netidx_value_v32(uint32_t v);

struct NetidxValue *netidx_value_i32(int32_t v);

struct NetidxValue *netidx_value_z32(int32_t v);

struct NetidxValue *netidx_value_u64(uint64_t v);

struct NetidxValue *netidx_value_v64(uint64_t v);

struct NetidxValue *netidx_value_i64(int64_t v);

struct NetidxValue *netidx_value_z64(int64_t v);

struct NetidxValue *netidx_value_f32(float v);

struct NetidxValue *netidx_value_f64(double v);

struct NetidxValue *netidx_value_bool(bool v);

/**
 * Create a Value::String from a UTF-8 byte range.
 * `data` does not need to be null-terminated; `len` bytes are used.
 */
struct NetidxValue *netidx_value_string(const char *data, uintptr_t len);

/**
 * Create a Value::Bytes from a raw byte range.
 */
struct NetidxValue *netidx_value_bytes(const uint8_t *data, uintptr_t len);

/**
 * Create a Value::Error wrapping another Value. Consumes `inner`.
 */
struct NetidxValue *netidx_value_error(struct NetidxValue *inner);

/**
 * Create a Value::Array from an array of Value pointers. Consumes all values.
 */
struct NetidxValue *netidx_value_array(struct NetidxValue *const *values, uintptr_t len);

/**
 * Create a Value::Map from parallel arrays of keys and values. Consumes all keys and values.
 */
struct NetidxValue *netidx_value_map(struct NetidxValue *const *keys,
                                     struct NetidxValue *const *values,
                                     uintptr_t len);

/**
 * Get the number of entries in a Map. Returns 0 if not a Map.
 */
uintptr_t netidx_value_map_len(const struct NetidxValue *val);

/**
 * Look up a key in a Map, returning a cloned value. Borrows both arguments.
 * Returns NULL if not a Map or key not found.
 */
struct NetidxValue *netidx_value_map_get_clone(const struct NetidxValue *val,
                                               const struct NetidxValue *key);

/**
 * Get all entries from a Map as parallel arrays of cloned keys and values.
 * Caller must free each array with netidx_value_array_free and each
 * value with netidx_value_destroy. Returns false if not a Map.
 */
bool netidx_value_map_entries_clone(const struct NetidxValue *val,
                                    struct NetidxValue ***out_keys,
                                    struct NetidxValue ***out_values,
                                    uintptr_t *out_len);

/**
 * Free an array of pointers returned by map_entries_clone, update receivers, etc.
 * Individual elements must be destroyed separately with their respective destroy functions.
 */
void netidx_value_array_free(struct NetidxValue **arr, uintptr_t len);

/**
 * Create a Value::Decimal by parsing a string like "3.14".
 * Returns NULL and sets error on parse failure.
 */
struct NetidxValue *netidx_value_decimal(const char *data, uintptr_t len, struct NetidxError *err);

/**
 * Get the string representation of a Decimal value.
 * Returns an allocated string that must be freed with netidx_str_free.
 * Returns false if not a Decimal.
 */
bool netidx_value_get_decimal_string(const struct NetidxValue *val, char **data, uintptr_t *len);

/**
 * Create a Value::DateTime from a UNIX timestamp (seconds since epoch + nanoseconds).
 */
struct NetidxValue *netidx_value_datetime(int64_t secs, uint32_t nsecs);

/**
 * Get the UNIX timestamp components of a DateTime value.
 * Returns false if not a DateTime.
 */
bool netidx_value_get_datetime(const struct NetidxValue *val, int64_t *secs, uint32_t *nsecs);

/**
 * Create a Value::Duration from seconds + nanoseconds.
 */
struct NetidxValue *netidx_value_duration(uint64_t secs, uint32_t nsecs);

/**
 * Get the components of a Duration value.
 * Returns false if not a Duration.
 */
bool netidx_value_get_duration(const struct NetidxValue *val, uint64_t *secs, uint32_t *nsecs);

/**
 * Get the UUID of an Abstract value as 16 raw bytes.
 * Returns false if not an Abstract.
 */
bool netidx_value_abstract_id(const struct NetidxValue *val, uint8_t (*out)[16]);

/**
 * Pack-encode an Abstract value to bytes.
 * Sets *out_data and *out_len. Caller must free with netidx_bytes_free.
 * Returns false if not an Abstract.
 */
bool netidx_value_abstract_encode(const struct NetidxValue *val,
                                  uint8_t **out_data,
                                  uintptr_t *out_len);

/**
 * Decode a Value::Abstract from Pack-encoded bytes.
 * The type must be registered in the process. Returns NULL on error.
 */
struct NetidxValue *netidx_value_abstract_decode(const uint8_t *data,
                                                 uintptr_t len,
                                                 struct NetidxError *err);

/**
 * Free bytes allocated by netidx_value_abstract_encode.
 */
void netidx_bytes_free(uint8_t *data, uintptr_t len);

/**
 * Get the type tag of a value.
 */
NetidxValueType netidx_value_type(const struct NetidxValue *val);

bool netidx_value_get_u8(const struct NetidxValue *val, uint8_t *out);

bool netidx_value_get_i8(const struct NetidxValue *val, int8_t *out);

bool netidx_value_get_u16(const struct NetidxValue *val, uint16_t *out);

bool netidx_value_get_i16(const struct NetidxValue *val, int16_t *out);

bool netidx_value_get_u32(const struct NetidxValue *val, uint32_t *out);

bool netidx_value_get_i32(const struct NetidxValue *val, int32_t *out);

bool netidx_value_get_u64(const struct NetidxValue *val, uint64_t *out);

bool netidx_value_get_i64(const struct NetidxValue *val, int64_t *out);

bool netidx_value_get_f32(const struct NetidxValue *val, float *out);

bool netidx_value_get_f64(const struct NetidxValue *val, double *out);

bool netidx_value_get_bool(const struct NetidxValue *val, bool *out);

/**
 * Get string data. Borrows from the Value — valid while the Value lives.
 * Returns false if not a String variant.
 */
bool netidx_value_get_string(const struct NetidxValue *val, const char **data, uintptr_t *len);

/**
 * Get bytes data. Borrows from the Value — valid while the Value lives.
 * Returns false if not a Bytes variant.
 */
bool netidx_value_get_bytes(const struct NetidxValue *val, const uint8_t **data, uintptr_t *len);

/**
 * Clone the inner value of an Error variant. Returns a new owned Value.
 * Returns NULL if not an Error.
 */
struct NetidxValue *netidx_value_get_error_clone(const struct NetidxValue *val);

/**
 * Get array length. Returns 0 if not an Array.
 */
uintptr_t netidx_value_array_len(const struct NetidxValue *val);

/**
 * Clone an element from an Array. Returns a new owned Value.
 * Returns NULL if not an Array or index out of bounds.
 */
struct NetidxValue *netidx_value_array_get_clone(const struct NetidxValue *val, uintptr_t index);

/**
 * Get the display string representation of a Value.
 * The returned string is newly allocated and must be freed with netidx_str_free.
 */
void netidx_value_to_string(const struct NetidxValue *val, char **data, uintptr_t *len);

/**
 * Free a string returned by netidx_value_to_string.
 */
void netidx_str_free(char *s);

/**
 * Clone a Value. Returns a new owned handle.
 */
struct NetidxValue *netidx_value_clone(const struct NetidxValue *val);

/**
 * Destroy a Value, freeing its memory.
 */
void netidx_value_destroy(struct NetidxValue *val);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NETIDX_H */
