[package]
name = "netidx-activation"
version = "0.32.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2024"
license = "MIT"
description = "netidx activation unit schema and runtime"
homepage = "https://netidx.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
readme = "../README.md"
documentation = "https://docs.rs/netidx-activation"
keywords = ["networking", "distributed", "activation"]
categories = ["network-programming"]

[dependencies]
anyhow = { workspace = true }
derive_builder = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
netidx = { path = "../netidx", version = "0.32.0", default-features = false }
netidx-core = { path = "../netidx-core", version = "0.32.0" }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }
